# Generated by Django 5.0.6 on 2024-07-15 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_alter_member_role_alter_team_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
        migrations.AddField(
            model_name='member',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='team.team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('GUEST', 'Guest'), ('LEADER', 'Leader'), ('MEMBER', 'Member'), ('MANAGER', 'Manager'), ('MODELER', 'Modeler'), ('CHECKER', 'Checker'), ('DETAILER', 'Detailer'), ('ERECTER', 'Erecter'), ('ADMIN', 'Admin')], default='GUEST', max_length=50, verbose_name='Role'),
        ),
    ]
