# Generated by Django 5.0.6 on 2024-07-05 10:08

import fabricator.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricator',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('8e00944b-3f13-4e86-bf4f-65c5bcc7bbfe'), editable=False, primary_key=True, serialize=False)),
                ('fabName', models.CharField(max_length=150, unique=True)),
                ('contactPerson', models.CharField(max_length=150)),
                ('contactPhone', models.CharField(max_length=13)),
                ('contactCountry', models.CharField(max_length=150)),
                ('contactState', models.CharField(max_length=150)),
                ('contactCity', models.CharField(max_length=150)),
                ('contract', models.FileField(null=True, upload_to=fabricator.models.contractUpload)),
            ],
        ),
    ]
