# Generated by Django 5.0.6 on 2024-07-05 10:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabricator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricator',
            name='id',
            field=models.UUIDField(default=uuid.UUID('145630f5-6311-45c7-ad15-6c6ca3104343'), editable=False, primary_key=True, serialize=False),
        ),
    ]
