# Generated by Django 5.0.6 on 2024-07-05 10:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabricator', '0002_alter_fabricator_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricator',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4f789f15-8007-4763-acc3-d04b4636a263'), editable=False, primary_key=True, serialize=False),
        ),
    ]
