# Generated by Django 5.0.6 on 2024-07-05 10:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabricator', '0003_alter_fabricator_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricator',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b033183d-40e1-4834-a258-f4fc03f089c1'), editable=False, primary_key=True, serialize=False),
        ),
    ]
