# Generated by Django 5.0.6 on 2024-07-05 10:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabricator', '0004_alter_fabricator_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricator',
            name='id',
            field=models.UUIDField(default=uuid.UUID('46f2d23a-6483-4627-83e8-c06dd7330a7e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
