# Generated by Django 5.0.6 on 2024-07-05 11:55

import fabricator.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabricator', '0008_alter_fabricator_contactcity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricator',
            name='contract',
            field=models.FileField(blank=True, null=True, upload_to=fabricator.models.contractUpload, verbose_name='Contract'),
        ),
        migrations.AlterField(
            model_name='fabricator',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d23ccad5-e645-4509-beac-25e6059a218c'), editable=False, primary_key=True, serialize=False),
        ),
    ]
