# Generated by Django 5.0.6 on 2024-07-05 11:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabricator', '0009_alter_fabricator_contract_alter_fabricator_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricator',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d5617971-6a07-4694-a0a6-268c746201c0'), editable=False, primary_key=True, serialize=False),
        ),
    ]
