# Generated by Django 5.0.6 on 2024-07-05 12:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabricator', '0011_alter_fabricator_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricator',
            name='id',
            field=models.UUIDField(default=uuid.UUID('64ebc81f-0128-4afb-98e3-3b31e57ce528'), editable=False, primary_key=True, serialize=False),
        ),
    ]
