# Generated by Django 5.0.6 on 2024-07-05 13:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabricator', '0012_alter_fabricator_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricator',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c849bfc1-b99f-443d-8c40-e06ca281943f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
