# Generated by Django 5.0.6 on 2024-07-05 14:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabricator', '0013_alter_fabricator_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricator',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2ef038b2-e907-4422-aebf-87ced84c5ada'), editable=False, primary_key=True, serialize=False),
        ),
    ]
