# Generated by Django 5.0.6 on 2024-07-05 14:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabricator', '0015_alter_fabricator_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricator',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0bae2939-9652-4fba-8025-a5f0eb22bedf'), editable=False, primary_key=True, serialize=False),
        ),
    ]
