# Generated by Django 5.0.6 on 2024-07-15 07:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabricator', '0016_alter_fabricator_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricator',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fd74af10-ca7f-4b96-bda4-f243282d2997'), editable=False, primary_key=True, serialize=False),
        ),
    ]
