# Generated by Django 5.0.6 on 2024-07-15 07:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabricator', '0017_alter_fabricator_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricator',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6f68459a-7b87-4cf6-9a9d-6c7f581e5fe4'), editable=False, primary_key=True, serialize=False),
        ),
    ]
