# Generated by Django 5.0.6 on 2024-07-15 07:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabricator', '0018_alter_fabricator_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricator',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7969c05b-5698-41cd-b7a8-7a57917ca804'), editable=False, primary_key=True, serialize=False),
        ),
    ]
