# Generated by Django 5.0.6 on 2024-07-15 08:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabricator', '0019_alter_fabricator_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricator',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7b82f4b4-2b73-4e30-8606-3d772a2739f5'), editable=False, primary_key=True, serialize=False),
        ),
    ]
