# Generated by Django 5.0.6 on 2024-07-15 10:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabricator', '0023_alter_fabricator_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricator',
            name='id',
            field=models.UUIDField(default=uuid.UUID('63c8e7dd-e9fa-4048-a7c2-38acbbaae3ae'), editable=False, primary_key=True, serialize=False),
        ),
    ]
