# Generated by Django 5.0.6 on 2024-07-15 10:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabricator', '0024_alter_fabricator_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricator',
            name='id',
            field=models.UUIDField(default=uuid.UUID('065ebc47-6308-4632-9d02-b3995b0e63c3'), editable=False, primary_key=True, serialize=False),
        ),
    ]
