# Generated by Django 5.0.6 on 2024-07-15 12:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabricator', '0025_alter_fabricator_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricator',
            name='id',
            field=models.UUIDField(default=uuid.UUID('81297288-fd7d-45ef-aa6a-3c2047071bbc'), editable=False, primary_key=True, serialize=False),
        ),
    ]
