# Generated by Django 5.0.6 on 2024-07-15 12:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabricator', '0026_alter_fabricator_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fabricator',
            old_name='fabName',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='fabricator',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b03802c4-e6fd-481c-9e0f-854ea39488e0'), editable=False, primary_key=True, serialize=False),
        ),
    ]
