# Generated by Django 5.0.6 on 2024-07-15 14:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabricator', '0027_rename_fabname_fabricator_name_alter_fabricator_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricator',
            name='id',
            field=models.UUIDField(default=uuid.UUID('18b57da4-f9d2-44c8-a279-1390a5a05908'), editable=False, primary_key=True, serialize=False),
        ),
    ]
