# Generated by Django 5.0.6 on 2024-07-17 11:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabricator', '0029_alter_fabricator_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricator',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a71121f6-7902-4c70-b684-44be2266d672'), editable=False, primary_key=True, serialize=False),
        ),
    ]
