# Generated by Django 5.0.6 on 2024-07-17 11:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabricator', '0030_alter_fabricator_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabricator',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6ed4da20-9b1a-45f4-ab2a-a02020ad6413'), editable=False, primary_key=True, serialize=False),
        ),
    ]
