# Generated by Django 5.0.6 on 2024-07-25 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabricator', '0034_rename_contactcity_fabricator_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactperson',
            old_name='PersonName',
            new_name='name',
        ),
    ]
