# Generated by Django 5.0.6 on 2024-07-25 07:40

import fabricator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabricator', '0035_rename_personname_contactperson_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricator',
            name='design',
            field=models.FileField(blank=True, null=True, upload_to=fabricator.models.contractUpload),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='designation',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='email',
            field=models.EmailField(blank=True, max_length=150, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='phone',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Phone Number'),
        ),
    ]
