# Generated by Django 5.0.6 on 2024-07-05 14:40

import django.db.models.deletion
import task.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabricator', '0014_alter_fabricator_id'),
        ('project', '0006_alter_project_description_alter_project_enddate_and_more'),
        ('task', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedlist',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approval Status'),
        ),
        migrations.AlterField(
            model_name='assignedlist',
            name='approved_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_by', to=settings.AUTH_USER_MODEL, verbose_name='Approved By'),
        ),
        migrations.AlterField(
            model_name='assignedlist',
            name='approved_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Approved On'),
        ),
        migrations.AlterField(
            model_name='assignedlist',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_by', to=settings.AUTH_USER_MODEL, verbose_name='Assigned By'),
        ),
        migrations.AlterField(
            model_name='assignedlist',
            name='assigned_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Assigned On'),
        ),
        migrations.AlterField(
            model_name='assignedlist',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to=settings.AUTH_USER_MODEL, verbose_name='Assigned To'),
        ),
        migrations.AlterField(
            model_name='assignedlist',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Comment on Approval'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assignes',
            field=models.ManyToManyField(blank=True, to='task.assignedlist', verbose_name='Assign List'),
        ),
        migrations.AlterField(
            model_name='task',
            name='child',
            field=models.ManyToManyField(blank=True, related_name='child_task', to='task.task', verbose_name='Child Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='comments',
            field=models.ManyToManyField(blank=True, to='task.taskcomment', verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.DurationField(verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='task',
            name='fabricator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fabricator.fabricator', verbose_name='Fabricator'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='task',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_task', to='task.task', verbose_name='Parent Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(max_length=255, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Current Assigne'),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Commented On'),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='data',
            field=models.TextField(blank=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='file',
            field=models.FileField(null=True, upload_to=task.models.uploadCommentFile, verbose_name='Attachment'),
        ),
        migrations.AlterField(
            model_name='taskcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Commented By'),
        ),
    ]
