# Generated by Django 5.0.6 on 2024-07-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_task_child_alter_task_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='child',
            field=models.ManyToManyField(blank=True, to='task.task', verbose_name='Child Task'),
        ),
    ]
