# Generated by Django 5.0.6 on 2024-07-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_task_attachment_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='child',
            field=models.ManyToManyField(blank=True, null=True, to='task.task', verbose_name='Child Task'),
        ),
    ]
