# Generated by Django 5.0.6 on 2024-07-15 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_alter_task_child'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='child',
        ),
    ]
