# Generated by Django 5.0.6 on 2024-07-15 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_alter_task_due_date_alter_task_parent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assignes',
        ),
        migrations.RemoveField(
            model_name='task',
            name='comments',
        ),
        migrations.AddField(
            model_name='assignedlist',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='task.task', verbose_name='Task'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskcomment',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='task.task', verbose_name='Task'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('ASSINGED', 'Assigned'), ('IN-PROGRESS', 'In Progress'), ('ON-HOLD', 'On Hold'), ('BREAK', 'Break'), ('IN-REVIEW', 'In Review'), ('COMPLETE', 'Completed'), ('APPROVED', 'Approved')], default='ASSIGNED', max_length=255, verbose_name='Status'),
        ),
    ]
