# Generated by Django 5.0.6 on 2024-07-15 14:14

import task.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_remove_task_assignes_remove_task_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskcomment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=task.models.uploadCommentFile, verbose_name='Attachment'),
        ),
    ]
