# Generated by Django 5.0.6 on 2024-07-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0012_alter_taskcomment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedlist',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Comment on Approval'),
        ),
    ]
