# Generated by Django 5.0.6 on 2024-07-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0014_alter_assignedlist_approved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedlist',
            name='approved_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approved On'),
        ),
    ]
