# Generated by Django 5.0.6 on 2024-07-05 10:08

import django.db.models.deletion
import project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fabricator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=255)),
                ('file', models.FileField(null=True, upload_to=project.models.uploadFile)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField(null=True)),
                ('status', models.CharField(default='active', max_length=55)),
                ('stage', models.CharField(default='IFA', max_length=55)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fabricator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabricator', to='fabricator.fabricator')),
            ],
        ),
    ]
