# Generated by Django 5.0.6 on 2024-07-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='stage',
            field=models.CharField(choices=[('IFA', 'Issue for Approval'), ('BFA', 'Back from Approval'), ('RIFA', 'Re-issue for Approval'), ('IFC', 'Issue for Construction'), ('BFC', 'Back from Construction'), ('RIFC', 'Re-issue for Construction'), ('RIF', 'Request for Information'), ('REV', 'Revision')], default='IFA', max_length=55),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('on-hold', 'On-Hold'), ('inactive', 'Inactive'), ('delayed', 'Delayed'), ('reopened', 'Reopened'), ('completed', 'Completed'), ('submitted', 'Submitted'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='active', max_length=55),
        ),
    ]
