# Generated by Django 5.0.6 on 2024-07-05 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabricator', '0014_alter_fabricator_id'),
        ('project', '0005_alter_project_created_at_alter_project_stage_and_more'),
        ('team', '0003_alter_member_role_alter_team_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, verbose_name='Project Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='endDate',
            field=models.DateTimeField(null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='fabricator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fabricator', to='fabricator.fabricator', verbose_name='Fabricator'),
        ),
        migrations.AlterField(
            model_name='project',
            name='files',
            field=models.ManyToManyField(blank=True, to='project.projectfile', verbose_name='Project Files'),
        ),
        migrations.AlterField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL, verbose_name='Project Manager'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='stage',
            field=models.CharField(blank=True, choices=[('IFA', 'Issue for Approval'), ('BFA', 'Back from Approval'), ('RIFA', 'Re-issue for Approval'), ('IFC', 'Issue for Construction'), ('BFC', 'Back from Construction'), ('RIFC', 'Re-issue for Construction'), ('RIF', 'Request for Information'), ('REV', 'Revision')], default='IFA', max_length=55, null=True, verbose_name='Project Stage'),
        ),
        migrations.AlterField(
            model_name='project',
            name='startDate',
            field=models.DateTimeField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('on-hold', 'On-Hold'), ('inactive', 'Inactive'), ('delayed', 'Delayed'), ('reopened', 'Reopened'), ('completed', 'Completed'), ('submitted', 'Submitted'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='active', max_length=55, null=True, verbose_name='Project Status'),
        ),
        migrations.AlterField(
            model_name='project',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team', verbose_name='Team'),
        ),
    ]
