# Generated by Django 5.0.6 on 2024-07-15 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_remove_project_files_projectfile_project'),
        ('team', '0005_alter_member_employee_alter_member_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('ACTIVE', 'Active'), ('ON-HOLD', 'On-Hold'), ('INACTIVE', 'Inactive'), ('DELAY', 'Delay'), ('REOPEN', 'Reopened'), ('COMPLETE', 'Complete'), ('SUBMIT', 'Submit'), ('SUSPEND', 'Suspend'), ('CANCEL', 'Cancel')], default='ACTIVE', max_length=55, null=True, verbose_name='Project Status'),
        ),
        migrations.AlterField(
            model_name='project',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='team.team', verbose_name='Team'),
        ),
    ]
