# Generated by Django 5.0.6 on 2024-07-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_project_status_alter_project_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Project Name'),
        ),
    ]
