# Generated by Django 5.0.6 on 2024-07-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='duration',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='endDate',
            field=models.DateTimeField(null=True, verbose_name='Approval Date'),
        ),
    ]
