# Generated by Django 5.0.6 on 2024-07-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_project_duration_alter_project_enddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tool',
            field=models.CharField(blank=True, choices=[('TEKLA', 'TEKLA'), ('SDS-2', 'SDS-2')], default=None, max_length=20, null=True, verbose_name='Tools'),
        ),
    ]
