# Generated by Django 5.0.6 on 2024-08-01 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_project_connectiondesign_project_miscdesign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='connectionDesign',
            field=models.BooleanField(default=False, verbose_name='Connection Design'),
        ),
        migrations.AlterField(
            model_name='project',
            name='miscDesign',
            field=models.BooleanField(default=False, verbose_name='Misc Design'),
        ),
        migrations.AlterField(
            model_name='project',
            name='stage',
            field=models.CharField(blank=True, choices=[('RFI', 'Request for Information'), ('IFA', 'Issue for Approval'), ('BFA', 'Back from Approval'), ('BFA-M', 'Back from Approval - Markup'), ('RIFA', 'Re-issue for Approval'), ('RBFA', 'Return Back from Approval'), ('IFC', 'Issue for Construction'), ('BFC', 'Back from Construction'), ('RIFC', 'Re-issue for Construction'), ('REV', 'Revision'), ('CO#', 'Completed')], default='IFA', max_length=55, null=True, verbose_name='Project Stage'),
        ),
    ]
