# Generated by Django 5.0.6 on 2024-07-05 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_userid_user_username_alter_user_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PuchRecord',
            new_name='PushRecord',
        ),
    ]
