# Generated by Django 5.0.6 on 2024-07-05 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_assignedlist_approved_and_more'),
        ('user', '0005_rename_puchrecord_pushrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushrecord',
            name='type',
            field=models.CharField(choices=[('START', 'Start'), ('END', 'End'), ('RESUME', 'Resume'), ('SUSPEND', 'Suspend')], max_length=255, verbose_name='Record Type'),
        ),
        migrations.AlterField(
            model_name='taskrecord',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.task', verbose_name='Task'),
        ),
        migrations.AlterField(
            model_name='taskrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, null=True, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Manager'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='Admin'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=150, null=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='Username'),
        ),
    ]
