# Generated by Django 5.0.6 on 2024-07-15 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_pushrecord_type_alter_taskrecord_task_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskrecord',
            name='punch',
        ),
        migrations.AddField(
            model_name='pushrecord',
            name='record',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.taskrecord'),
            preserve_default=False,
        ),
    ]
